UI animations
hatchways/team-naan-bread pull request #68
Opened 2021-09-11 17:07 UTC by serafy0

### What this PR does (required):
- added grow animations to some components

### Screenshots / Videos (required):
https://user-images.githubusercontent.com/29197126/132955603-26221031-bd22-4680-b0b2-60b0d00a54ff.mov

### Any information needed to test this feature (required):

### Any issues with the current functionality (optional):
- this is still a work on progress.

2021-09-13 12:58 UTC, serafy0 commented
added skeleton loading animation for notifications 

https://user-images.githubusercontent.com/29197126/133086160-be983fe3-609d-4543-9d83-6510a9d738e0.mov


https://user-images.githubusercontent.com/29197126/133085635-eacc9364-a6e5-4162-832d-8819025d2132.mov

2021-09-14 04:22 UTC, moffatethan reviewed
Please address my comments and going forward please be cautious of the following.

1. We should be naming our PR titles more descriptively - "UI animations" but it has notifications work in it. The context is hard and makes it hard for me to know what I am reviewing exactly.
2. Ensuring we aren't pushing duplicated code for review (#67) code is in this PR.

2021-09-14 04:22 UTC, moffatethan commented on client/src/components/NavBar/NavBar.tsx
> +              {/*{if profile.type == sitter}*/}
Remove please 😄

2021-09-14 04:22 UTC, moffatethan commented on client/src/components/NavBar/NotificationsMenu/NotificationsMenuItems/NotificationsMenuItems.tsx
> +            <Box key={index} paddingLeft={'4px'}>
Given we can receive notifications and so indexes change this is actually an anti-pattern to use indexes as keys - please use something more unique such as the notification id.

2021-09-14 04:22 UTC, moffatethan commented on client/src/helpers/APICalls/Notification.ts
> +};
I would just use async/await here as opposed to mixing .then and async/await.

2021-09-14 04:22 UTC, moffatethan commented on client/src/helpers/APICalls/Notification.ts
> +};
Same here

2021-09-14 04:22 UTC, moffatethan commented on client/src/helpers/APICalls/Notification.ts
> +};
Same here

2021-09-14 04:22 UTC, moffatethan commented on client/src/pages/Profile/Profile.tsx
> +  console.log('path:', path, 'url:', url);
Remove please, is this duplicated from #67

2021-09-16 20:10 UTC, serafy0 commented
If i changed the base branch to `main` again will most of those duplicated code be removed ?
I think the problem i did was branching from https://github.com/hatchways/team-naan-bread/pull/67 and then merging https://github.com/hatchways/team-naan-bread/pull/63 into this pull request

2021-09-17 04:16 UTC, moffatethan requested changes
So close, please work on the merge conflicts and then I will give approval.

2021-09-18 06:22 UTC, moffatethan approved these changes

2021-09-18 09:02 UTC, merged