Pet profile route+controller
hatchways/team-naan-bread pull request #89
Opened 2021-09-27 22:06 UTC by konradkop

### What this PR does (required):
- Created the Route and Controller for Pet Profiles
- 
### Screenshots / Videos (required):
![petprofile](https://user-images.githubusercontent.com/67756235/134991830-661b2d8c-d5c3-4a51-897e-7572cfa8dd25.PNG)

2021-09-27 22:34 UTC, moffatethan commented
I've updated the base of the branch to the pet model branch, this reduces the file sizes and keeps things more concise 😄

2021-09-27 22:46 UTC, moffatethan requested changes
Overall good, let's just do that readability change 😄 👍🏻

2021-09-27 22:46 UTC, moffatethan commented on server/controllers/petProfile.js
> +     for(let prop in values) if(!values[prop]) delete values[prop];//it will remove fields who are undefined or null
This isn't very readable, could we make it a bit more readable?

2021-09-28 04:19 UTC, konradkop commented
> Another thing, I would like to see middleware validation on the incoming data. We should be validating all incoming data we are accepting from users to ensure reliability in our codebase.

OK, I've added the jwt authentication middlewere that was in the codebase as well as some type checks

2021-09-29 00:58 UTC, moffatethan approved these changes
LGTM

2021-09-30 16:27 UTC, merged