FE: Pet Meetup Events
hatchways/team-naan-bread pull request #90
Opened 2021-09-29 18:10 UTC by serafy0

### What this PR does (required):
- front end components for [pet meetup ticket](https://github.com/hatchways/team-naan-bread/issues/83)
- added Google Maps support using [@react-google-maps/api](https://www.npmjs.com/package/@react-google-maps/api) library 
-  added three new pages
   - `petEventPage`: shows the location and information about a specific event
   - `NearByPetEvents`: when the user allows the app to get his coordinates, it should return his location on the map and nearby events
   - `PetEventForm`: a form for creating or editing pet meetup events
### Screenshots / Videos (required):

<img width="1280" alt="Screen Shot 2021-09-29 at 7 46 16 PM" src="https://user-images.githubusercontent.com/29197126/135322212-dd5b938b-e748-494f-907e-ff49d822ef03.png">
<img width="1144" alt="Screen Shot 2021-09-29 at 7 45 17 PM" src="https://user-images.githubusercontent.com/29197126/135322217-7f78340f-90f1-436f-936e-ff91fc17fa66.png">
<img width="1257" alt="Screen Shot 2021-09-29 at 7 45 48 PM" src="https://user-images.githubusercontent.com/29197126/135322186-e1564907-6b96-42bd-80bd-9906cd124bf7.png">

### Any information needed to test this feature (required):
- login in a user and go to `/events` to see nearby events or go to `/event` an info about one event.
- this branch  only uses mock data for events for now.

2021-10-01 20:09 UTC, ezeilo-su commented
Please resolve merge conflict on this PR before your code can be reviewed.

2021-10-01 22:25 UTC, ezeilo-su reviewed
Congrats on finishing this one. Just resolve the merge conflict in the PR.
Happy coding!

2021-10-01 22:25 UTC, ezeilo-su commented on client/src/components/PetEvent/mockData.tsx
> +    { _id: '1', email: 'sample@sample.com', firstName: 'attendee3' } as ProfileApiData,
Since you have different attendees here, it would be more readable and intuitive to use a unique `_id` for each entry.

2021-10-01 22:27 UTC, ezeilo-su requested changes
Resolve merge conflict, please.

2021-10-01 22:32 UTC, serafy0 commented
Sorry for being late, I've just tried to resolve the merge conflict between this branch and main

2021-10-01 23:09 UTC, ezeilo-su reviewed
Good one implementing those changes. Good luck with your next project.

2021-10-04 16:49 UTC, moffatethan approved these changes
Good work!

2021-10-04 18:23 UTC, merged